name: Danger
on:
  pull_request_target:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  # deployments: read
  issues: write
  pull-requests: write
  statuses: write

jobs:
  run-danger:
    name: run-danger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - name: Setup gems
        run: gem install danger
      - name: Run Danger
        run: danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
