name: Danger
on:
  pull_request_target:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  # deployments: read
  issues: write
  pull-requests: write
  statuses: write

jobs:
  run-danger:
    name: run-danger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - uses: MeilCli/danger-action@v5
        with:
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
          danger_version: '>= 6.0.0'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
