name: Danger
on:
  - pull_request_target

permissions:
  pull-requests: write
  statuses: write

jobs:
  run-danger:
    name: run-danger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.heads.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: danger/danger@master
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
